_description: |
  A block of content which has an image, a title, text and footer. All elements are stacked and are the full width of whichever container they appear in.


text: &default
  _placeholder:
    height: 50px
    text: Add Text Here
    required: true
  _has:
    input: inline
    type: multi-component
    buttons:
      - bold
      - italic
      - strike
      - link

title: *default

prologue:
  _label: Header Image
  _has:
    input: text
    type: url
    help: An image for an image to appear above the title

epilogue:
  _label: Footer Image
  _has:
    input: text
    type: url

_groups:
  settings:
    fields:
      - prologue
      - epilogue
