_description: |
  The footer at the bottom of all pages.
_confirmRemoval: true

socialMediaLinks:
  _label: Social Media Links
  _placeholder:
    text: New Follow
    height: 50px
  _has:
    input: complex-list
    props:
      -
        prop: socialMediaNetwork
        _label: socialMediaNetwork
        _has:
          input: radio
          help: Select the network for this follow button
          options:
                - Facebook
                - Twitter
                - Instagram
      -
        prop: url
        _label: Social Media Handle
        _has:
            input: text
            type: url
            validate:
              required: true

navegationLinks:
  _label: Navegation Links
  _placeholder:
    text: Navegation Links
    height: 50px
  _has:
    input: complex-list
    props:
      -
        prop: url
        _label: Url
        _has:
          input: text
          type: url
          validate:
            required: true
      -
        prop: text
        _label: Link Text
        _has:
          input: text
          enforceMaxlength: true
          validate:
            required: true
            max: 40
            maxMessage: This field must be 40 or fewer characters long

siteLogo:
  _label: Site Logo
  _placeholder:
    height: 50px
  _has:
    input: text
    help: support svg

logoUrl:
  _label: Logo URL
  _placeholder:
    height: 50px
  _has:
    input: text

_groups:
  settings:
    fields:
      - siteLogo (General)
      - logoUrl (General)
      - navegationLinks (Navegation Links)
    _placeholder:
      text: Footer
      height: 30px
      ifEmpty: logoUrl
